Update t2.yml

diff --git a/.github/workflows/t2.yml b/.github/workflows/t2.yml
--- a/.github/workflows/t2.yml
+++ b/.github/workflows/t2.yml
@@ -17,3 +17,10 @@ jobs:
         run: |
           ls ${{ github.workspace }}
       - run: echo "🍏 This job's status is ${{ job.status }}."
+      run |
+        http_response=$(curl -s -o response.txt -w "%{http_code}" http://deprem.francecentral.cloudapp.azure.com:8080/survey/questionlist)
+        if [ $http_response != "200" ]; then
+            echo "error && exit 1"
+        else
+            echo "OK"    
+        fi
